In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [4]:
df.shape

(1470, 35)

In [5]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [6]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [9]:
for col in df.select_dtypes(include='object').columns:
    print("\n", col)
    print(df[col].unique())

 Attrition
['Yes' 'No']

 BusinessTravel
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']

 Department
['Sales' 'Research & Development' 'Human Resources']

 EducationField
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']

 Gender
['Female' 'Male']

 JobRole
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']

 MaritalStatus
['Single' 'Married' 'Divorced']

 Over18
['Y']

 OverTime
['Yes' 'No']

In [10]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [11]:
(df["YearsAtCompany"] > df["TotalWorkingYears"]).sum()

0

In [12]:
(df["YearsInCurrentRole"] > df["YearsAtCompany"]).sum()

0

In [13]:
df = df.drop(columns=["EmployeeCount", "Over18", "StandardHours"])

In [14]:
df.shape

(1470, 32)

In [15]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [16]:
rating_cols = [
    "EnvironmentSatisfaction",
    "JobInvolvement",
    "JobSatisfaction",
    "RelationshipSatisfaction",
    "WorkLifeBalance",
    "PerformanceRating"
]

df[rating_cols].agg(["min", "max"])

,EnvironmentSatisfaction,JobInvolvement,JobSatisfaction,RelationshipSatisfaction,WorkLifeBalance,PerformanceRating
min,1,1,1,1,1,3
max,4,4,4,4,4,4

In [17]:
df.to_csv("HR_Employee_Attrition_Cleaned.csv", index=False)

In [18]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [19]:
attrition_rate = (237 / 1470) * 100
print(attrition_rate)

16.122448979591837

In [20]:
df["Attrition"].value_counts(normalize=True) * 100

Attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

In [21]:
df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [22]:
df.groupby("Department")["Attrition"].value_counts()

Department              Attrition
Human Resources         No            51
                        Yes           12
Research & Development  No           828
                        Yes          133
Sales                   No           354
                        Yes           92
Name: count, dtype: int64

In [23]:
df.groupby("OverTime")["Attrition"].value_counts()

OverTime  Attrition
No        No           944
          Yes          110
Yes       No           289
          Yes          127
Name: count, dtype: int64

In [24]:
df.groupby("JobRole")["Attrition"].value_counts()

JobRole                    Attrition
Healthcare Representative  No           122
                           Yes            9
Human Resources            No            40
                           Yes           12
Laboratory Technician      No           197
                           Yes           62
Manager                    No            97
                           Yes            5
Manufacturing Director     No           135
                           Yes           10
Research Director          No            78
                           Yes            2
Research Scientist         No           245
                           Yes           47
Sales Executive            No           269
                           Yes           57
Sales Representative       No            50
                           Yes           33
Name: count, dtype: int64

In [25]:
job_role_attrition = (
    df.groupby("JobRole")["Attrition"]
      .apply(lambda x: (x == "Yes").mean() * 100)
      .round(2)
)

print(job_role_attrition)

JobRole
Healthcare Representative     6.87
Human Resources              23.08
Laboratory Technician        23.94
Manager                       4.90
Manufacturing Director        6.90
Research Director             2.50
Research Scientist           16.10
Sales Executive              17.48
Sales Representative         39.76
Name: Attrition, dtype: float64

In [26]:
df["TenureGroup"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0-2 years", "3-5 years", "6-10 years", "11+ years"]
)
df["TenureGroup"].value_counts().sort_index()

TenureGroup
0-2 years     342
3-5 years     434
6-10 years    448
11+ years     246
Name: count, dtype: int64

In [27]:
df.groupby("TenureGroup")["Attrition"].value_counts()

C:\Users\kalya\AppData\Local\Temp\ipykernel_24564\1249705610.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("TenureGroup")["Attrition"].value_counts()

TenureGroup  Attrition
0-2 years    No           240
             Yes          102
3-5 years    No           374
             Yes           60
6-10 years   No           393
             Yes           55
11+ years    No           226
             Yes           20
Name: count, dtype: int64

In [28]:
tenure_attrition = (
    df.groupby("TenureGroup")["Attrition"]
      .apply(lambda x: (x == "Yes").mean() * 100)
      .round(2)
)

print(tenure_attrition)

TenureGroup
0-2 years     29.82
3-5 years     13.82
6-10 years    12.28
11+ years      8.13
Name: Attrition, dtype: float64

C:\Users\kalya\AppData\Local\Temp\ipykernel_24564\3976067751.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("TenureGroup")["Attrition"]

In [6]:

df.groupby("Attrition")["MonthlyIncome"].agg(["count", "mean", "median", "min", "max"]).round(2)

NameError: name 'df' is not defined

NameError: name 'df' is not defined

In [7]:
import pandas as pd

df = pd.read_csv("HR_Employee_Attrition_Cleaned.csv")

In [8]:
df.shape

(1470, 32)

In [9]:
df["TenureGroup"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0-2 years", "3-5 years", "6-10 years", "11+ years"]
)

In [10]:
df.groupby("Attrition")["MonthlyIncome"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

           count     mean  median   min    max
Attrition
No          1233  6832.74  5204.0  1051  19999
Yes          237  4787.09  3202.0  1009  19859

In [11]:
role_income_attrition = (
    df.groupby("JobRole")
      .agg(
          Employees=("EmployeeNumber", "count"),
          AvgIncome=("MonthlyIncome", "mean"),
          AttritionRate=("Attrition", lambda x: (x == "Yes").mean() * 100)
      )
      .round(2)
)

print(role_income_attrition)

                           Employees  AvgIncome  AttritionRate
JobRole
Healthcare Representative        131    7528.76           6.87
Human Resources                   52    4235.75          23.08
Laboratory Technician            259    3237.17          23.94
Manager                          102   17181.68           4.90
Manufacturing Director           145    7295.14           6.90
Research Director                 80   16033.55           2.50
Research Scientist               292    3239.97          16.10
Sales Executive                  326    6924.28          17.48
Sales Representative              83    2626.00          39.76

In [12]:
df.groupby("JobLevel")["Attrition"].apply(
    lambda x: (x == "Yes").mean() * 100
).round(2)

JobLevel
1    26.34
2     9.74
3    14.68
4     4.72
5     7.25
Name: Attrition, dtype: float64

In [13]:
pd.crosstab(df["TenureGroup"], df["JobLevel"])

JobLevel       1    2   3   4   5
TenureGroup
0-2 years    215   80  27   9  11
3-5 years    209  161  34  20  10
6-10 years   102  223  93  20  10
11+ years     17   70  64  57  38

In [14]:
df["TenureGroup"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0-2 years", "3-5 years", "6-10 years", "11+ years"]
)

In [15]:
pd.crosstab(df["TenureGroup"], df["JobLevel"])

JobLevel       1    2   3   4   5
TenureGroup
0-2 years    215   80  27   9  11
3-5 years    209  161  34  20  10
6-10 years   102  223  93  20  10
11+ years     17   70  64  57  38

In [16]:
tenure_job_attrition = (
    df.groupby(["TenureGroup", "JobLevel"])["Attrition"]
      .apply(lambda x: (x == "Yes").mean() * 100)
      .round(2)
)

print(tenure_job_attrition)

TenureGroup  JobLevel
0-2 years    1           36.74
             2           20.00
             3           22.22
             4           11.11
             5            0.00
3-5 years    1           19.62
             2            8.70
             3           11.76
             4            0.00
             5           10.00
6-10 years   1           21.57
             2            8.52
             3           15.05
             4            0.00
             5            0.00
11+ years    1            5.88
             2            4.29
             3           12.50
             4            7.02
             5           10.53
Name: Attrition, dtype: float64

C:\Users\kalya\AppData\Local\Temp\ipykernel_11844\4001924212.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["TenureGroup", "JobLevel"])["Attrition"]

In [17]:
df[
    (df["TenureGroup"] == "0-2 years") &
    (df["JobLevel"] == 1)
].groupby("OverTime")["Attrition"].value_counts()

OverTime  Attrition
No        No           111
          Yes           39
Yes       Yes           40
          No            25
Name: count, dtype: int64

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("HR_Employee_Attrition_Cleaned.csv")

In [3]:
df.shape

(1470, 32)

In [4]:
pd.crosstab(
    df["JobSatisfaction"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition               No        Yes
JobSatisfaction
1                77.162630  22.837370
2                83.571429  16.428571
3                83.484163  16.515837
4                88.671024  11.328976

In [5]:
df.groupby("JobSatisfaction")["Attrition"].value_counts()

JobSatisfaction  Attrition
1                No           223
                 Yes           66
2                No           234
                 Yes           46
3                No           369
                 Yes           73
4                No           407
                 Yes           52
Name: count, dtype: int64

In [6]:
pd.crosstab(
    df["EnvironmentSatisfaction"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                       No        Yes
EnvironmentSatisfaction
1                        74.647887  25.352113
2                        85.017422  14.982578
3                        86.313466  13.686534
4                        86.547085  13.452915

In [7]:
pd.crosstab(
    df["WorkLifeBalance"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition               No        Yes
WorkLifeBalance
1                68.750000  31.250000
2                83.139535  16.860465
3                85.778275  14.221725
4                82.352941  17.647059

In [1]:
import pandas as pd

df = pd.read_csv("HR_Employee_Attrition_Cleaned.csv")

In [2]:
df["WorkLifeBalance"].value_counts().sort_index()

WorkLifeBalance
1     80
2    344
3    893
4    153
Name: count, dtype: int64

In [3]:
pd.crosstab(
    df["JobInvolvement"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition              No        Yes
JobInvolvement
1               66.265060  33.734940
2               81.066667  18.933333
3               85.599078  14.400922
4               90.972222   9.027778

In [4]:
df["JobInvolvement"].value_counts().sort_index()

JobInvolvement
1     83
2    375
3    868
4    144
Name: count, dtype: int64

In [5]:
pd.crosstab(
    df["BusinessTravel"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                 No        Yes
BusinessTravel
Non-Travel         92.000000   8.000000
Travel_Frequently  75.090253  24.909747
Travel_Rarely      85.043145  14.956855

In [6]:
df["BusinessTravel"].value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [7]:
df["DistanceGroup"] = pd.cut(
    df["DistanceFromHome"],
    bins=[0, 5, 10, 20, 100],
    labels=["0-5 km", "6-10 km", "11-20 km", "20+ km"]
)

In [8]:
df["DistanceGroup"].value_counts().sort_index()

DistanceGroup
0-5 km      632
6-10 km     394
11-20 km    240
20+ km      204
Name: count, dtype: int64

In [9]:
pd.crosstab(
    df["DistanceGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition             No        Yes
DistanceGroup
0-5 km         86.234177  13.765823
6-10 km        85.532995  14.467005
11-20 km       80.000000  20.000000
20+ km         77.941176  22.058824

In [10]:
df["JobLevel"].value_counts().sort_index()

JobLevel
1    543
2    534
3    218
4    106
5     69
Name: count, dtype: int64

In [11]:
pd.crosstab(
    df["JobLevel"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition         No        Yes
JobLevel
1          73.664825  26.335175
2          90.262172   9.737828
3          85.321101  14.678899
4          95.283019   4.716981
5          92.753623   7.246377

In [12]:
df["MonthlyIncome"].describe()

count     1470.000000
mean      6502.931293
std       4707.956783
min       1009.000000
25%       2911.000000
50%       4919.000000
75%       8379.000000
max      19999.000000
Name: MonthlyIncome, dtype: float64

In [13]:
df["IncomeGroup"] = pd.qcut(
    df["MonthlyIncome"],
    q=4,
    labels=["Low", "Lower-Middle", "Upper-Middle", "High"]
)

In [14]:
df["IncomeGroup"].value_counts().sort_index()

IncomeGroup
Low             369
Lower-Middle    366
Upper-Middle    367
High            368
Name: count, dtype: int64

In [15]:
pd.crosstab(
    df["IncomeGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition            No        Yes
IncomeGroup
Low           70.731707  29.268293
Lower-Middle  85.792350  14.207650
Upper-Middle  89.373297  10.626703
High          89.673913  10.326087

In [16]:
df["Age"].describe()

count    1470.000000
mean       36.923810
std         9.135373
min        18.000000
25%        30.000000
50%        36.000000
75%        43.000000
max        60.000000
Name: Age, dtype: float64

In [17]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[17, 25, 35, 45, 60],
    labels=["18-25", "26-35", "36-45", "46-60"]
)

In [18]:
df["AgeGroup"].value_counts().sort_index()

AgeGroup
18-25    123
26-35    606
36-45    468
46-60    273
Name: count, dtype: int64

In [19]:
pd.crosstab(
    df["AgeGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition         No        Yes
AgeGroup
18-25      64.227642  35.772358
26-35      80.858086  19.141914
36-45      90.811966   9.188034
46-60      87.545788  12.454212

In [20]:
df["YearsAtCompany"].describe()

count    1470.000000
mean        7.008163
std         6.126525
min         0.000000
25%         3.000000
50%         5.000000
75%         9.000000
max        40.000000
Name: YearsAtCompany, dtype: float64

In [21]:
df["TenureGroup"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0-2 years", "3-5 years", "6-10 years", "11+ years"]
)

In [22]:
df["TenureGroup"].value_counts().sort_index()

TenureGroup
0-2 years     342
3-5 years     434
6-10 years    448
11+ years     246
Name: count, dtype: int64

In [23]:
pd.crosstab(
    df["TenureGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition           No        Yes
TenureGroup
0-2 years    70.175439  29.824561
3-5 years    86.175115  13.824885
6-10 years   87.723214  12.276786
11+ years    91.869919   8.130081

In [24]:
df["YearsSinceLastPromotion"].describe()

count    1470.000000
mean        2.187755
std         3.222430
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max        15.000000
Name: YearsSinceLastPromotion, dtype: float64

In [25]:
df["PromotionGapGroup"] = pd.cut(
    df["YearsSinceLastPromotion"],
    bins=[-1, 1, 3, 5, float("inf")],
    labels=["0-1 years", "2-3 years", "4-5 years", "6+ years"]
)

In [26]:
df["PromotionGapGroup"].value_counts().sort_index()

PromotionGapGroup
0-1 years    938
2-3 years    211
4-5 years    106
6+ years     215
Name: count, dtype: int64

In [27]:
pd.crosstab(
    df["PromotionGapGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                 No        Yes
PromotionGapGroup
0-1 years          83.049041  16.950959
2-3 years          82.938389  17.061611
4-5 years          93.396226   6.603774
6+ years           83.720930  16.279070

In [28]:
df["JobRole"].value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

In [29]:
pd.crosstab(
    df["JobRole"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                         No        Yes
JobRole
Healthcare Representative  93.129771   6.870229
Human Resources            76.923077  23.076923
Laboratory Technician      76.061776  23.938224
Manager                    95.098039   4.901961
Manufacturing Director     93.103448   6.896552
Research Director          97.500000   2.500000
Research Scientist         83.904110  16.095890
Sales Executive            82.515337  17.484663
Sales Representative       60.240964  39.759036

In [30]:
df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [31]:
pd.crosstab(
    df["Department"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                      No        Yes
Department
Human Resources         80.952381  19.047619
Research & Development  86.160250  13.839750
Sales                   79.372197  20.627803

In [32]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

In [33]:
pd.crosstab(
    df["MaritalStatus"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition             No        Yes
MaritalStatus
Divorced       89.908257  10.091743
Married        87.518574  12.481426
Single         74.468085  25.531915

In [34]:
df["NumCompaniesWorked"].describe()

count    1470.000000
mean        2.693197
std         2.498009
min         0.000000
25%         1.000000
50%         2.000000
75%         4.000000
max         9.000000
Name: NumCompaniesWorked, dtype: float64

In [35]:
df["CompaniesWorkedGroup"] = pd.cut(
    df["NumCompaniesWorked"],
    bins=[-1, 1, 3, 5, float("inf")],
    labels=["0-1", "2-3", "4-5", "6+"]
)

In [36]:
df["CompaniesWorkedGroup"].value_counts()

CompaniesWorkedGroup
0-1    718
2-3    305
6+     245
4-5    202
Name: count, dtype: int64

In [37]:
pd.crosstab(
    df["CompaniesWorkedGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                    No        Yes
CompaniesWorkedGroup
0-1                   83.147632  16.852368
2-3                   89.508197  10.491803
4-5                   83.663366  16.336634
6+                    79.183673  20.816327

In [38]:
df["StockOptionLevel"].value_counts().sort_index()

StockOptionLevel
0    631
1    596
2    158
3     85
Name: count, dtype: int64

In [39]:
pd.crosstab(
    df["StockOptionLevel"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                No        Yes
StockOptionLevel
0                 75.594295  24.405705
1                 90.604027   9.395973
2                 92.405063   7.594937
3                 82.352941  17.647059

In [40]:
df["TrainingTimesLastYear"].describe()

count    1470.000000
mean        2.799320
std         1.289271
min         0.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         6.000000
Name: TrainingTimesLastYear, dtype: float64

In [41]:
df["TrainingGroup"] = pd.cut(
    df["TrainingTimesLastYear"],
    bins=[-1, 1, 3, float("inf")],
    labels=["0-1", "2-3", "4+"]
)

In [42]:
df["TrainingGroup"].value_counts()

TrainingGroup
2-3    1038
4+      307
0-1     125
Name: count, dtype: int64

In [43]:
pd.crosstab(
    df["TrainingGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition             No        Yes
TrainingGroup
0-1            80.800000  19.200000
2-3            83.911368  16.088632
4+             85.016287  14.983713

In [44]:
df["PerformanceRating"].value_counts().sort_index()

PerformanceRating
3    1244
4     226
Name: count, dtype: int64

In [45]:
pd.crosstab(
    df["PerformanceRating"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                 No        Yes
PerformanceRating
3                  83.922830  16.077170
4                  83.628319  16.371681

In [46]:
df["EducationField"].value_counts()

EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

In [47]:
pd.crosstab(
    df["EducationField"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                No        Yes
EducationField
Human Resources   74.074074  25.925926
Life Sciences     85.313531  14.686469
Marketing         77.987421  22.012579
Medical           86.422414  13.577586
Other             86.585366  13.414634
Technical Degree  75.757576  24.242424

In [48]:
df["TotalWorkingYears"].describe()

count    1470.000000
mean       11.279592
std         7.780782
min         0.000000
25%         6.000000
50%        10.000000
75%        15.000000
max        40.000000
Name: TotalWorkingYears, dtype: float64

In [49]:
df["ExperienceGroup"] = pd.cut(
    df["TotalWorkingYears"],
    bins=[-1, 2, 5, 10, 20, float("inf")],
    labels=["0-2 years", "3-5 years", "6-10 years", "11-20 years", "21+ years"]
)

In [50]:
df["ExperienceGroup"].value_counts()

ExperienceGroup
6-10 years     607
11-20 years    340
21+ years      207
3-5 years      193
0-2 years      123
Name: count, dtype: int64

In [51]:
pd.crosstab(
    df["ExperienceGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition               No        Yes
ExperienceGroup
0-2 years        56.097561  43.902439
3-5 years        80.829016  19.170984
6-10 years       85.008237  14.991763
11-20 years      88.529412  11.470588
21+ years        92.270531   7.729469

In [52]:
df["YearsInCurrentRole"].describe()

count    1470.000000
mean        4.229252
std         3.623137
min         0.000000
25%         2.000000
50%         3.000000
75%         7.000000
max        18.000000
Name: YearsInCurrentRole, dtype: float64

In [53]:
df["CurrentRoleGroup"] = pd.cut(
    df["YearsInCurrentRole"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0-2 years", "3-5 years", "6-10 years", "11+ years"]
)

In [54]:
df["CurrentRoleGroup"].value_counts()

CurrentRoleGroup
0-2 years     673
6-10 years    444
3-5 years     275
11+ years      78
Name: count, dtype: int64

In [55]:
pd.crosstab(
    df["CurrentRoleGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                No        Yes
CurrentRoleGroup
0-2 years         77.414562  22.585438
3-5 years         88.363636  11.636364
6-10 years        89.189189  10.810811
11+ years         93.589744   6.410256

In [56]:
df["YearsWithCurrManager"].describe()

count    1470.000000
mean        4.123129
std         3.568136
min         0.000000
25%         2.000000
50%         3.000000
75%         7.000000
max        17.000000
Name: YearsWithCurrManager, dtype: float64

In [57]:
df["ManagerTenureGroup"] = pd.cut(
    df["YearsWithCurrManager"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0-2 years", "3-5 years", "6-10 years", "11+ years"]
)

In [58]:
df["ManagerTenureGroup"].value_counts()

ManagerTenureGroup
0-2 years     683
6-10 years    443
3-5 years     271
11+ years      73
Name: count, dtype: int64

In [59]:
pd.crosstab(
    df["ManagerTenureGroup"],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                  No        Yes
ManagerTenureGroup
0-2 years           78.623719  21.376281
3-5 years           87.453875  12.546125
6-10 years          87.810384  12.189616
11+ years           95.890411   4.109589

In [60]:
pd.crosstab(
    [df["OverTime"], df["JobSatisfaction"]],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                        No        Yes
OverTime JobSatisfaction
No       1                82.439024  17.560976
         2                90.521327   9.478673
         3                90.031153   9.968847
         4                93.059937   6.940063
Yes      1                64.285714  35.714286
         2                62.318841  37.681159
         3                66.115702  33.884298
         4                78.873239  21.126761

In [61]:
pd.crosstab(
    [df["JobRole"], df["OverTime"]],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                                  No        Yes
JobRole                   OverTime
Healthcare Representative No        92.553191   7.446809
                          Yes       94.594595   5.405405
Human Resources           No        82.051282  17.948718
                          Yes       61.538462  38.461538
Laboratory Technician     No        84.263959  15.736041
                          Yes       50.000000  50.000000
Manager                   No        98.666667   1.333333
                          Yes       85.185185  14.814815
Manufacturing Director    No        94.339623   5.660377
                          Yes       89.743590  10.256410
Research Director         No        98.245614   1.754386
                          Yes       95.652174   4.347826
Research Scientist        No        92.820513   7.179487
                          Yes       65.979381  34.020619
Sales Executive           No        88.793103  11.206897
                          Yes       67.021277  32.978723
Sales Representative      No        71.186441  28.813559
                          Yes       33.333333  66.666667

In [62]:
pd.crosstab(
    [df["JobLevel"], df["IncomeGroup"]],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                     No        Yes
JobLevel IncomeGroup
1        Low           69.943820  30.056180
         Lower-Middle  80.874317  19.125683
         Upper-Middle  75.000000  25.000000
2        Low           92.307692   7.692308
         Lower-Middle  90.710383   9.289617
         Upper-Middle  90.614887   9.385113
         High          82.758621  17.241379
3        Upper-Middle  83.333333  16.666667
         High          85.975610  14.024390
4        High          95.283019   4.716981
5        High          92.753623   7.246377

In [63]:
pd.crosstab(
    [df["TenureGroup"], df["OverTime"]],
    df["Attrition"],
    normalize="index"
) * 100

Attrition                    No        Yes
TenureGroup OverTime
0-2 years   No        79.411765  20.588235
            Yes       49.038462  50.961538
3-5 years   No        92.182410   7.817590
            Yes       71.653543  28.346457
6-10 years  No        92.682927   7.317073
            Yes       74.166667  25.833333
11+ years   No        92.817680   7.182320
            Yes       89.230769  10.769231

In [64]:
sales_rep = df[df["JobRole"] == "Sales Representative"]

pd.crosstab(
    sales_rep["JobLevel"],
    sales_rep["Attrition"],
    normalize="index"
) * 100

Attrition         No        Yes
JobLevel
1          57.894737  42.105263
2          85.714286  14.285714